### ISSUE TITLE
dinger class is empty

### ISSUE THREAD

**Issue by ponphy** [AnswerAIL/dingtalk-spring-boot-starter#12]
JRE:
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

SpringBoot: 2.2.1.RELEASE

dinger打包成二方包后，类加载出错

错误堆栈：
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at com.github.jaemon.dinger.utils.PackageUtils.forClassNames(PackageUtils.java:108)
	at com.github.jaemon.dinger.utils.PackageUtils.classNames(PackageUtils.java:78)
	at com.github.jaemon.dinger.core.spring.DingerScannerRegistrar.registerBeanDefinitions(DingerScannerRegistrar.java:74)
	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:385)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)

**Comment by ponphy** [comment]
![image](https://user-images.githubusercontent.com/11926876/115851074-22ee0180-a459-11eb-845e-03aad7efb46f.png)


解析自定义Dinger报错：java.lang.IllegalArgumentException: URI is not hierarchical

**Comment by ponphy** [comment]
升级到 1.1.1-beta1 版本解决
