### ISSUE TITLE
springboot1.x   启动报错

### ISSUE THREAD

**Issue by randolph555** [AnswerAIL/dingtalk-spring-boot-starter#8]
<dependency>
            <groupId>com.github.answerail</groupId>
            <artifactId>dingtalk-spring-boot-starter</artifactId>
            <version>3.0.0-RELEASE</version>
        </dependency>

 
 @Component
 public class InitializingBeanExecute implements InitializingBean {

    @Resource
    private DingTalkSender dingTalkSender;

    @Override
    public void afterPropertiesSet() {
        String keyword = "DYZ3AALTRBD2AIDLL0Y3EQ4TYGLJDUM";
        String subTitle = "服务启动通知";
        String content = "服务启动啦。。。";

        // text类型
        dingTalkSender.send(MsgTypeEnum.TEXT, keyword, subTitle, content);

        // markdown类型
        dingTalkSender.send(MsgTypeEnum.MARKDOWN, keyword, subTitle, content);
    }

   spring.dingtalk.token-id=xxx
  spring.dingtalk.monitor.success=true
  spring.dingtalk.monitor.falied=true
  spring.dingtalk.project-id=${spring.application.name}
  spring.dingtalk.async=true

Exception in thread "main" java.lang.NoSuchMethodError: org.springframework.boot.SpringApplication.getAllSources()Ljava/util/Set;
	at com.jaemon.dingtalk.listeners.StartEventListener.onApplicationEvent(StartEventListener.java:45)
	at com.jaemon.dingtalk.listeners.StartEventListener.onApplicationEvent(StartEventListener.java:34)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)

**Comment by AnswerAIL** [comment]
请使用spring2.X版本，1.x还没做适配，因为这个方法springboot 1.x中没有，我本地开发测试的springboot版本是2.0.3.RELEASE

**Comment by randolph555** [comment]
> 请使用spring2.X版本，1.x还没做适配，因为这个方法springboot 1.x中没有，我本地开发测试的springboot版本是2.0.3.RELEASE

能出springboot1.x的兼容嘛？ 应该是ApplicationHome这个的问题

**Comment by AnswerAIL** [comment]
可以，后面会进行适配的

**Comment by AnswerAIL** [comment]
@randolph555
请下载springboot1.x适配版本[dingtalk-spring-boot-starter-3.0.0-SP1](https://gitee.com/jaemon/docs/raw/master/dingtalk-spring-boot-starter-3.0.0-SP1.jar)并在本地进行验证，谢谢

**Comment by AnswerAIL** [comment]
https://github.com/AnswerAIL/dingtalk-spring-boot-starter/issues/8#issuecomment-739834979

**Comment by AnswerAIL** [comment]
https://github.com/AnswerAIL/dingtalk-spring-boot-starter/issues/8#issuecomment-739834979

**Comment by AnswerAIL** [comment]
issues #8
